import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import Astrounauta from "~/assets/Group.png";
import Torus2 from "~/assets/Torus2.png";
import Torus from "~/assets/torus.png";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-white min-h-screen items-center flex justify-center">
          <div className="flex shadow-md border border-[#E6E9FA] rounded-3xl relative">
            <Image
              src={Torus}
              alt=""
              quality={100}
              className="absolute top-1/2 -translate-y-1/2 -translate-x-1/2 left-0"
            />
            <Image
              src={Torus2}
              alt=""
              quality={100}
              className="absolute bottom-0 translate-y-1/2 right-[243px] translate-x-1/2"
            />
            <div className="w-[732px] h-[743px] bg-[#3949AB] items-center flex flex-col justify-center gap-8 rounded-l-3xl">
              <Image src={Astrounauta} alt="" quality={100} />
              <p className="text-white font-semibold">Bem vindo, amigo!</p>
              <p className="text-white font-medium text-base">
                Apenas mais uns cliques e começamos
              </p>
            </div>
            <div className="w-[486px] h-[743px] bg-white/20 backdrop-blur-md p-10 rounded-r-3xl relative isolate">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
